---
title: "Titre de votre page d'exploration"
title-block-banner: false
description: | 
  Petite description de cette page.
# à changer
date: "2022-12-21"
# Modifier les détails que vous voulez
author:
  - name: "Prénom Nom"
    # Votre site web perso ou github
    url: https://github.com/VOTREUSERNAME
    # les champs d'affiliation sont optionnels, vous pouvez les
    # comment out en ajoutant un # devant.
    affiliation: FAS1002
    affiliation-url: https://FAS1002.github.io/A22
    # changer pour votre propre orcid id
    # https://orcid.org/ pour vous inscrire.
    orcid: 0000-0000-0000-0000

# TRUE == Générer une citation pour cette page précise. Pour enlever, mettre false.
citation: true
# Inclure les références que vous utilisez dans vos rapports. Je conseille Zotero pour construire
# ce fichier ou de connecter RStudio directement pour pouvoir citer avec @nom-de-reference.
bibliography: references.bib
---

## Réimporter les données

```{r echo=FALSE, warning=FALSE,message=FALSE}

library(tidyverse)
library(fs)
library(lubridate)
library(skimr)
```

```{r read}
df <- read_csv(file = "data/raw/2022-12-06_owid-co2-data.csv")
skim(df)
```

## Données extrêmes

On peut voir dans la catégorie `age` la personne la plus vieille aurait 97 ans. Est-ce vrai ou est-ce coder pour quelque chose de différent?

```{r}
# p1 <- ggplot(data = df,
#        aes(x = Age))
# 
# p1 + geom_bar(color = "black",
#               fill = "#facade")
```

```{r}
# df |> 
#     filter(Age >= 79) |> 
#     select(Name, Age, Team, Games, Sport, Sex)
```

## Age vs Sex

```{r}
# p2 <- ggplot(data = df,
#              aes(x = Sex,
#                  y = Age))
# p2 + geom_boxplot()
```

## Ration H:F au courant des années

```{r}
# evolution <- df |> 
#     group_by(Year, Sex) |> 
#     summarise(n = n()) |> 
#     mutate(pourcentage = n/sum(n)*100)
# 
# evolution
```
