---
title: "Titre de votre page d'importation"
title-block-banner: true
description: | 
  Petite description de cette page.
# à changer
date: "2022-12-21"
# Modifier les détails que vous voulez
author:
  - name: "Prénom Nom"
    # Votre site web perso ou github
    url: https://github.com/VOTREUSERNAME
    # les champs d'affiliation sont optionnels, vous pouvez les
    # comment out en ajoutant un # devant.
    affiliation: FAS1002
    affiliation-url: https://FAS1002.github.io/A22
    # changer pour votre propre orcid id
    # https://orcid.org/ pour vous inscrire.
    orcid: 0000-0000-0000-0000

# TRUE == Générer une citation pour cette page précise. Pour enlever, mettre false.
citation: true
# Inclure les références que vous utilisez dans vos rapports. Je conseille Zotero pour construire
# ce fichier ou de connecter RStudio directement pour pouvoir citer avec @nom-de-reference.
bibliography: references.bib
---

```{r echo=FALSE, warning=FALSE,message=FALSE}

library(tidyverse)
library(fs)
library(lubridate)
library(skimr)
```

```{r download, cache=TRUE}
#option cache=TRUE c'est si le code ne change pas, il ne devrait pas redownloader le fichier

URL <- "https://github.com/owid/co2-data/blob/master/owid-co2-data.csv"

base_path <- path("data", "raw") # pour que nimporte qui puisse download avec le chemin relatif

fname <- paste(today(), "owid-co2-data.csv", sep = "_") # pour find name

fpath <- path(base_path, fname) # matcher le bon nom dans le bon path

data <- download.file(url = URL, destfile = fpath)
```

V1 : Le fichier a été téléchargé ici : `data/raw/2022-12-06_owid-co2-data.csv`

V2 :V1 : Le fichier a été téléchargé ici : `r fpath` (permet d'update automatiquement le nom mis en haut)

```{r extraction}

unzip(zipfile = fpath) # pour changer de directory
```
