---
title: "Projet final du cours FAS1002"
---
## Présentation

Dans le cadre de ce travail final [^1], nous avons exploré deux banques de données, provenant de deux sources distinctes, _Our World in Data_ et _GapMinder_.

[^1]:Le travail a été réalisé en collaboration entre Cécile Amadoro et Juliette Leblanc

Provenance des données:

> La première banque de données provient de @owidenergy et se trouvent [ici](https://ourworldindata.org/co2-emissions)

> La seconde provient de @gmlifeexpectancy et se trouvent [ici](https://www.gapminder.org/)

Les autres pages du site web sont consacrées première à [l'analyse](intro.qmd), [l'importation](import.qmd) et la [manipualtion des données](exploration.qmd) pour créer les stastistiques descriptives ainsi que les analyses qui seront présentées dans la section [analyse](intro.qmd).

Si vous souhaitez reproduire les analyses, tout le matériel à cet effet est disponible. Nous vous recommandons de commencer par l'importation des données et ensuite l'exploration pour en arrivé finalement à l'analyse. 

NB : Le code utilisé se trouve dans les bribes, il ne suffit que de les ouvrir pour voir la démarche. Le code a été produit en `R`.


## Vous pourrez inclure des graphiques

Comme la classique pyramide à la ci-dessous par exemple:

```{r pie, fig.cap='Une très belle tarte', tidy=FALSE}
par(mar = c(0, 1, 0, 1))
pie(
  c(280, 60, 20),
  c('Ciel', 'Côté ensoleillé de la pyramide', 'Côté ombragé de la pyramide'),
  col = c('#0292D8', '#F7EA39', '#C4B632'),
  init.angle = -50, border = NA
)
```

<aside>Quand même très cool, non? Vous pouvez mettre des annotations sur le côté!</aside>



## Remerciements {.appendix}

Nous aimerions remercier notre enseignant Samuel Guay pour sa patience incroyable, son aide et ses astuces de programmation tout au long de la session ! 
